import { registerGame } from './registry.js';
import { randomInt, escapeHtml, tone, vibrate } from '../core/utils.js';
import { bindExit, stageHeader } from './shared.js';
const plugin={
 id:'dice',title:'命运骰局',sortOrder:3,icon:'dice',color:'#a78bfa',minPlayers:2,maxPlayers:12,supportsAdult:true,estimatedTime:'1–3 分钟',shortDescription:'轮流投骰，点数决定本轮输家。',description:'玩家按派对房间顺序轮流投骰。全部完成后，根据“最高点输”或“最低点输”判定本轮遭殃的人。',phoneMode:'依次传递手机',resultMode:'选出本轮惩罚玩家',defaultSettings:{loserRule:'high',level:'standard'},
 renderSetup(settings){return `<div class="setting-block"><div class="setting-label"><span>输家规则</span><small>如何判定</small></div><div class="segmented" data-rule><button type="button" data-segment data-value="high" class="${settings.loserRule==='high'?'active':''}">最高点输</button><button type="button" data-segment data-value="low" class="${settings.loserRule==='low'?'active':''}">最低点输</button></div></div>`},
 readSetup(sheet){return {loserRule:sheet.querySelector('[data-rule] .active')?.dataset.value||'high'}},
 mount(root,ctx){let index=0,rolls=[];const render=()=>{const player=ctx.players[index];root.innerHTML=`${stageHeader(plugin.title,`${ctx.players.length} 人 · ${ctx.settings.loserRule==='high'?'最高点输':'最低点输'}`)}<section class="game-stage centered"><div class="turn-progress">第 ${Math.min(index+1,ctx.players.length)} / ${ctx.players.length} 位</div><span class="current-player">${escapeHtml(player?.name||'本轮完成')}</span><div class="dice-face" data-die>${rolls[index]?.value||'?'}</div><button class="button primary large" data-roll ${!player?'disabled':''}>投掷骰子</button>${rolls.length?`<div class="score-strip">${rolls.map(r=>`<span>${escapeHtml(r.player.name)} <b>${r.value}</b></span>`).join('')}</div>`:''}</section>`;bindExit(root,ctx);root.querySelector('[data-roll]')?.addEventListener('click',roll)};
 const roll=async()=>{const button=root.querySelector('[data-roll]'),die=root.querySelector('[data-die]');button.disabled=true;let ticks=0;const timer=setInterval(()=>{die.textContent=randomInt(1,6);die.classList.toggle('shake');tone(180+ticks*12,.025,ctx.global.sound,.018);ticks++},55);await new Promise(r=>setTimeout(r,650));clearInterval(timer);const value=randomInt(1,6);die.textContent=value;die.classList.remove('shake');vibrate([25,30,25],ctx.global.haptics);rolls.push({player:ctx.players[index],value});index++;await new Promise(r=>setTimeout(r,520));if(index>=ctx.players.length)finish();else render()};
 const finish=()=>{const target=ctx.settings.loserRule==='high'?Math.max(...rolls.map(r=>r.value)):Math.min(...rolls.map(r=>r.value));const tied=rolls.filter(r=>r.value===target);const loser=tied[randomInt(0,tied.length-1)].player;root.innerHTML=`${stageHeader(plugin.title)}<section class="game-stage centered"><span class="eyebrow">本轮结果</span><h2>${escapeHtml(loser.name)} 遭殃</h2><div class="result-number">${target}</div>${tied.length>1?'<p>同点玩家中已随机选出一位。</p>':''}<button class="button primary full" data-punish>抽取惩罚</button><button class="button secondary full" data-next>再来一轮</button></section>`;bindExit(root,ctx);root.querySelector('[data-punish]').onclick=()=>ctx.punishment([loser],{onDone:reset});root.querySelector('[data-next]').onclick=reset};
 const reset=()=>{index=0;rolls=[];render()};render();}
};registerGame(plugin);export default plugin;
