import { registerGame } from './registry.js';
import { drawGame } from '../modules/questions.js';
import { escapeHtml, shuffle, randomInt, tone, vibrate } from '../core/utils.js';
import { bindExit, passScreen, stageHeader } from './shared.js';
const speechOptions=[0,15,30,45,60];
const plugin={
 id:'undercover',title:'谁是卧底',sortOrder:5,icon:'mask',color:'#34d399',minPlayers:4,maxPlayers:12,supportsAdult:true,estimatedTime:'8–20 分钟',shortDescription:'私密看词、限时发言、投票找出卧底。',description:'经典多人推理玩法。玩家依次私密查看身份，按顺序限时描述，再秘密投票淘汰可疑玩家。',phoneMode:'逐人私密传递',resultMode:'阵营胜负',defaultSettings:{undercoverCount:1,blank:false,speechSeconds:30,level:'standard'},levelOptions:['light','standard','bold','adult'],
 renderSetup(settings){return `<div class="setting-block"><div class="setting-label"><span>卧底人数</span><small>建议每 6 人 1 名</small></div><div class="time-stepper"><button type="button" data-uc-minus>−</button><input data-uc-count type="number" min="1" max="3" value="${settings.undercoverCount||1}"><button type="button" data-uc-plus>＋</button></div></div><div class="setting-block"><div class="setting-label"><span>发言时限</span><small>默认 30 秒</small></div><div class="segmented wrap" data-speech>${speechOptions.map(n=>`<button type="button" data-segment data-value="${n}" class="${Number(settings.speechSeconds)===n?'active':''}">${n?`${n}秒`:'不限时'}</button>`).join('')}</div></div>`},
 bindSetup(sheet){const input=sheet.querySelector('[data-uc-count]');sheet.querySelector('[data-uc-minus]').onclick=()=>input.value=Math.max(1,Number(input.value)-1);sheet.querySelector('[data-uc-plus]').onclick=()=>input.value=Math.min(3,Number(input.value)+1)},
 readSetup(sheet){return {undercoverCount:Number(sheet.querySelector('[data-uc-count]').value||1),speechSeconds:Number(sheet.querySelector('[data-speech] .active')?.dataset.value||30)}},
 async mount(root,ctx){
  const settings={...ctx.settings,undercoverCount:Math.min(ctx.settings.undercoverCount||1,Math.max(1,ctx.players.length-2))};
  const pair=await drawGame('undercover',settings.level);
  let alive=[...ctx.players],roles=new Map(),viewIndex=0,speakerIndex=0,voterIndex=0,votes=[],round=1,timer=null;
  const undercoverIds=new Set(shuffle(ctx.players).slice(0,settings.undercoverCount).map(p=>p.id));
  ctx.players.forEach(p=>roles.set(p.id,undercoverIds.has(p.id)?'undercover':'civilian'));
  const startView=()=>{viewIndex=0;renderPass()};
  const renderPass=()=>{const player=ctx.players[viewIndex];root.innerHTML=`${stageHeader(plugin.title,'私密查看身份')}${passScreen(player,'查看身份与词语')}`;bindExit(root,ctx);root.querySelector('[data-private-open]').onclick=()=>renderRole(player)};
  const renderRole=player=>{const role=roles.get(player.id),word=role==='undercover'?pair.undercover:pair.civilian;root.innerHTML=`${stageHeader(plugin.title)}<section class="private-stage secret-card"><span class="eyebrow">${escapeHtml(player.name)}</span><p>你的身份</p><h2 class="role-name ${role}">${role==='undercover'?'卧底':'平民'}</h2><div class="secret-word">${escapeHtml(word)}</div><p>不要直接说出词语，也不要让其他人看到。</p><button class="button primary full" data-remember>我记住了</button></section>`;bindExit(root,ctx);root.querySelector('[data-remember]').onclick=()=>{viewIndex++;viewIndex>=ctx.players.length?readySpeech():renderPass()}};
  const readySpeech=()=>{speakerIndex=0;root.innerHTML=`${stageHeader(plugin.title,`第 ${round} 轮发言`)}<section class="game-stage centered"><span class="eyebrow">身份查看完成</span><h2>开始轮流描述</h2><p>请避免直接说出词语。发言按派对房间中的存活玩家顺序进行。</p><button class="button primary full" data-speak>开始发言</button></section>`;bindExit(root,ctx);root.querySelector('[data-speak]').onclick=renderSpeaker};
  const renderSpeaker=()=>{const player=alive[speakerIndex];let remain=settings.speechSeconds;root.innerHTML=`${stageHeader(plugin.title,`第 ${round} 轮发言`)}<section class="game-stage centered"><span class="eyebrow">当前发言</span><h2>${escapeHtml(player.name)}</h2>${remain?`<div class="speech-timer" data-time>${remain}</div>`:'<div class="speech-timer unlimited">∞</div>'}<p>描述自己的词语，但不要直接说出答案。</p><button class="button primary full" data-finish>提前结束发言</button></section>`;bindExit(root,ctx);root.querySelector('[data-finish]').onclick=nextSpeaker;if(remain){const started=performance.now();const frame=now=>{remain=Math.max(0,settings.speechSeconds-(now-started)/1000);const n=Math.ceil(remain);root.querySelector('[data-time]')?.replaceChildren(String(n));if(n<=5&&n>0)tone(400+n*40,.03,ctx.global.sound,.02);if(remain>0)timer=requestAnimationFrame(frame);else{vibrate([40,30,40],ctx.global.haptics);nextSpeaker()}};timer=requestAnimationFrame(frame);ctx.onCleanup(()=>cancelAnimationFrame(timer))}};
  function nextSpeaker(){cancelAnimationFrame(timer);speakerIndex++;speakerIndex>=alive.length?readyVote():renderSpeaker()}
  const readyVote=()=>{voterIndex=0;votes=[];root.innerHTML=`${stageHeader(plugin.title,`第 ${round} 轮投票`)}<section class="game-stage centered"><span class="eyebrow">发言结束</span><h2>进入秘密投票</h2><p>每位存活玩家依次选择一名最可疑的人。</p><button class="button primary full" data-vote>开始投票</button></section>`;bindExit(root,ctx);root.querySelector('[data-vote]').onclick=votePass};
  const votePass=()=>{const voter=alive[voterIndex];root.innerHTML=`${stageHeader(plugin.title)}${passScreen(voter,'进入秘密投票')}`;bindExit(root,ctx);root.querySelector('[data-private-open]').onclick=()=>voteScreen(voter)};
  const voteScreen=voter=>{root.innerHTML=`${stageHeader(plugin.title)}<section class="private-stage"><span class="eyebrow">${escapeHtml(voter.name)} 的投票</span><h2>谁最像卧底？</h2><div class="player-choice-grid">${alive.filter(p=>p.id!==voter.id).map(p=>`<button data-candidate="${p.id}">${escapeHtml(p.name)}</button>`).join('')}</div></section>`;bindExit(root,ctx);root.querySelectorAll('[data-candidate]').forEach(b=>b.onclick=()=>{votes.push(b.dataset.candidate);voterIndex++;voterIndex>=alive.length?revealVote():votePass()})};
  const revealVote=()=>{const counts=new Map(alive.map(p=>[p.id,0]));votes.forEach(id=>counts.set(id,(counts.get(id)||0)+1));const max=Math.max(...counts.values());const tied=alive.filter(p=>counts.get(p.id)===max);const eliminated=tied[randomInt(0,tied.length-1)];alive=alive.filter(p=>p.id!==eliminated.id);const role=roles.get(eliminated.id);const underAlive=alive.filter(p=>roles.get(p.id)==='undercover').length,civAlive=alive.length-underAlive;const win=underAlive===0?'civilian':underAlive>=civAlive?'undercover':null;root.innerHTML=`${stageHeader(plugin.title)}<section class="game-stage centered"><span class="eyebrow">投票结果</span><h2>${escapeHtml(eliminated.name)} 被淘汰</h2><p class="result-callout">身份：${role==='undercover'?'卧底':'平民'}</p>${win?`<h3>${win==='civilian'?'平民阵营获胜':'卧底阵营获胜'}</h3><p>平民词：${escapeHtml(pair.civilian)} · 卧底词：${escapeHtml(pair.undercover)}</p><button class="button primary full" data-new>重新开局</button>`:`<button class="button primary full" data-next>进入下一轮发言</button>`}</section>`;bindExit(root,ctx);root.querySelector('[data-new]')?.addEventListener('click',()=>plugin.mount(root,ctx));root.querySelector('[data-next]')?.addEventListener('click',()=>{round++;readySpeech()})};
  document.addEventListener('visibilitychange',guard);ctx.onCleanup(()=>document.removeEventListener('visibilitychange',guard));function guard(){if(document.hidden&&root.querySelector('.secret-card'))renderPass()}
  startView();
 }
};registerGame(plugin);export default plugin;
